#

f_loadoptions_BuBaRTD <- function() {
  temp <- data.frame(
    names = c(
      # RPODUCTION
      "Produzierendes Gewerbe ohne Bau",
      "Produzierendes Gewerbe",
      "Baugewerbe",
      "Bauhauptgewerbe",
      "Ausbaugewerbe",
      "Industrie",
      "Vorleistungsgüter",
      "Investitionsgüter",
      "Konsumgüter",
      "Gebrauchsgüter",
      "Verbrauchsgüter",
      "Energie",
      "Hochbau",
      "Tiefbau",
      # ORDERS
      "Bauhauptgewerbe",
      "Industrie",
      "Vorleistungsgüter",
      "Investitionsgüter",
      "Konsumgüter",
      "Hochbau",
      "Tiefbau",
      "Wohnungsbau",
      "Bauhauptgewerbe, gewerbliche Auftraggeber",
      "Bauhauptgewerbe, öffentliche Auftraggeber und Straßenbau",
      "Industrie (Inland)",
      "Vorleistungsgüter (Inland)",
      "Investitionsgüter (Inland)",
      "Konsumgüter (Inland)",
      "Industrie (Ausland)",
      "Vorleistungsgüter (Ausland)",
      "Investitionsgüter (Ausland)",
      "Konsumgüter (Ausland)",
      # TURNOVER
      "Bauhauptgewerbe",
      "Industrie",
      "Vorleistungsgüter",
      "Investitionsgüter",
      "Konsumgüter",
      "Gebrauchsgüter",
      "Verbrauchsgüter",
      "Wohnungsbau",
      "Bauhauptgewerbe, gewerbliche Auftraggeber",
      "Bauhauptgewerbe, öffentliche Auftraggeber und Straßenbau",
      "Einzelhandel (ohne KFZ)",
      "Einzelhandel",
      "Handel mit KFZ",
      "Industrie (Inland)",
      "Vorleistungsgüter (Inland)",
      "Investitionsgüter (Inland)",
      "Konsumgüter (Inland)",
      "Industrie (Ausland)",
      "Vorleistungsgüter (Ausland)",
      "Investitionsgüter (Ausland)",
      "Konsumgüter (Ausland)",
      # PRICES
      "VPI: insgesamt",
      "VPI: insgesamt (ex Energie)",
      "VPI: insgesamt (ex Energie und Nahrungsmittel)",
      "VPI: Nahrungsmittel",
      "VPI: andere Gebrauchs- und Verbrauchsgüter",
      "VPI: Energie",
      "VPI: Dienstleistungen",
      "VPI: Dienstleistungen",
      "VPI: Mieten",
      "VPI: Mieten (ex Nebenkosten)",
      "PPI: industrielle Produkte",
      "PPI: industrielle Produkte (ex Energie)",
      "PPI: landwirtschaftliche Produkte",
      "Exportpreise",
      "Importpreise",
      # LABOR MARKET
      "Erwerbstätige: Verarbeitendes Gewerbe und Bergbau",
      #"Erwerbstätige: Bauhauptgewerbe",
      "Erwerbstätige: Gesamtwirtschaft",
      "Erwerbstätigenstunden: Verarbeitendes Gewerbe und Bergbau",
      "Erwerbstätigenstunden: Bauhauptgewerbe",
      "Sozialversichungspflichtig Beschäftigte",
      "BLG: Verarbeitendes Gewerbe und Bergbau",
      "BLG: Bauhauptgewerbe",
      # NATIONAL ACCOUNTS
      "Gross Domestic Product"),
    groups = c(
      rep("production", 14),
      rep("orders", 18),
      rep("turnover", 21),
      rep("prices", 15),
      rep("labor market", 7), # 8
      rep("national accounts", 1)),
    trafo = c(rep(3, 76)), # 77
    type = c(rep("m", 75), "q:E"), # 76
    flag_usestartvals = c(rep(1, 75), 0), # 76
    flag_sa = c(rep(0, 76)), # 77
    seriesnames = c(
      # RPODUCTION
      "BBKRT.M.DE.Y.I.IP1.AA020.C.I",
      "BBKRT.M.DE.Y.I.IP1.AA021.C.I",
      "BBKRT.M.DE.Y.I.IP1.AA030.C.I",
      "BBKRT.M.DE.Y.I.IP1.AA031.C.I",
      "BBKRT.M.DE.Y.I.IP1.AA032.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM01.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM02.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM03.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM04.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM05.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM06.C.I",
      "BBKRT.M.DE.Y.I.IP1.ACM07.C.I",
      "BBKRT.M.DE.Y.I.IP1.AFC11.C.I",
      "BBKRT.M.DE.Y.I.IP1.AFC12.C.I",
      # ORDERS
      "BBKRT.M.DE.Y.I.IO1.AA031.C.I",
      "BBKRT.M.DE.Y.I.IO1.ACM01.C.I",
      "BBKRT.M.DE.Y.I.IO1.ACM02.C.I",
      "BBKRT.M.DE.Y.I.IO1.ACM03.C.I",
      "BBKRT.M.DE.Y.I.IO1.ACM04.C.I",
      "BBKRT.M.DE.Y.I.IO1.AFC11.C.I",
      "BBKRT.M.DE.Y.I.IO1.AFC12.C.I",
      "BBKRT.M.DE.Y.I.IO1.AFC15.C.I",
      "BBKRT.M.DE.Y.I.IO1.AFC21.C.I",
      "BBKRT.M.DE.Y.I.IO1.AFC22.C.I",
      "BBKRT.M.DE.Y.I.IO2.ACM01.C.I",
      "BBKRT.M.DE.Y.I.IO2.ACM02.C.I",
      "BBKRT.M.DE.Y.I.IO2.ACM03.C.I",
      "BBKRT.M.DE.Y.I.IO2.ACM04.C.I",
      "BBKRT.M.DE.Y.I.IO3.ACM01.C.I",
      "BBKRT.M.DE.Y.I.IO3.ACM02.C.I",
      "BBKRT.M.DE.Y.I.IO3.ACM03.C.I",
      "BBKRT.M.DE.Y.I.IO3.ACM04.C.I",
      # TURNOVER
      "BBKRT.M.DE.Y.I.IT1.AA031.V.A",
      "BBKRT.M.DE.Y.I.IT1.ACM01.V.I",
      "BBKRT.M.DE.Y.I.IT1.ACM02.V.I",
      "BBKRT.M.DE.Y.I.IT1.ACM03.V.I",
      "BBKRT.M.DE.Y.I.IT1.ACM04.V.I",
      "BBKRT.M.DE.Y.I.IT1.ACM05.V.I",
      "BBKRT.M.DE.Y.I.IT1.ACM06.V.I",
      "BBKRT.M.DE.Y.I.IT1.AFC15.V.A",
      "BBKRT.M.DE.Y.I.IT1.AFC21.V.A",
      "BBKRT.M.DE.Y.I.IT1.AFC22.V.A",
      "BBKRT.M.DE.Y.I.IT1.AGA01.C.I",
      "BBKRT.M.DE.Y.I.IT1.AGC02.C.I",
      "BBKRT.M.DE.Y.I.IT1.AGD01.C.I",
      "BBKRT.M.DE.Y.I.IT2.ACM01.V.I",
      "BBKRT.M.DE.Y.I.IT2.ACM02.V.I",
      "BBKRT.M.DE.Y.I.IT2.ACM03.V.I",
      "BBKRT.M.DE.Y.I.IT2.ACM04.V.I",
      "BBKRT.M.DE.Y.I.IT3.ACM01.V.I",
      "BBKRT.M.DE.Y.I.IT3.ACM02.V.I",
      "BBKRT.M.DE.Y.I.IT3.ACM03.V.I",
      "BBKRT.M.DE.Y.I.IT3.ACM04.V.I",
      # PRICES
      "BBKRT.M.DE.Y.P.PC1.PC100.R.I",
      "BBKRT.M.DE.S.P.PC1.PC110.R.I",
      "BBKRT.M.DE.Y.P.PC1.PC120.R.I",
      "BBKRT.M.DE.S.P.PC1.PC200.R.I",
      "BBKRT.M.DE.S.P.PC1.PC300.R.I",
      "BBKRT.M.DE.Y.P.PC1.PC400.R.I",
      "BBKRT.M.DE.Y.P.PC1.PC500.R.I",
      "BBKRT.M.DE.Y.P.PC1.PC510.R.I",
      "BBKRT.M.DE.S.P.PC1.PC600.R.I",
      "BBKRT.M.DE.S.P.PC1.PC610.R.I",
      "BBKRT.M.DE.S.P.PP1.PP100.R.I",
      "BBKRT.M.DE.S.P.PP1.PP200.R.I",
      "BBKRT.M.DE.S.P.PP1.PP400.R.I",
      "BBKRT.M.DE.S.P.CX1.PP000.R.I",
      "BBKRT.M.DE.S.P.CM1.PP000.R.I",
      # LABOR MARKET
      "BBKRT.M.DE.S.L.BE1.AA022.P.I",
      #"BBKRT.M.DE.S.L.BE1.AA031.P.A",
      "BBKRT.M.DE.S.L.BE1.CA010.P.A",
      "BBKRT.M.DE.Y.L.BE2.AA022.H.I",
      "BBKRT.M.DE.Y.L.BE2.AA031.H.A",
      "BBKRT.M.DE.S.L.BG1.CA010.P.A",
      "BBKRT.M.DE.Y.L.DE2.AA022.V.I",
      "BBKRT.M.DE.Y.L.DE2.AA031.V.A",
      # NATIONAL ACCOUNTS
      "BBKRT.Q.DE.Y.A.AG1.CA010.A.I"))
  
  data <- list(
    names = as.character(temp$names),
    groups = as.character(temp$groups),
    trafo = as.numeric(temp$trafo),
    type = as.character(temp$type),
    flag_usestartvals = as.numeric(temp$flag_usestartvals),
    flag_sa = as.numeric(temp$flag_sa),
    seriesnames = as.character(temp$seriesnames))
  
 
   return(data)
}
